#Filename layouts.kv
<Button>:
	font_size:24
	size_hint:0.15,0.2
<FloatLayout>:
	Button:
		text:'Forward'
		pos_hint:{'x':0.65,'y':0.65}
	Button:
		text:'Reverse'
		pos_hint:{'x':0.65,'y':0.15}
	Button:
		text:'Turn right'
		pos_hint:{'x':0.80,'y':0.4}
	Button:
		text:'Turn left'
		pos_hint:{'x':0.50,'y':0.4}
	Button:
		text:'HODOR!'
		pos_hint:{'x':0.1,'y':0.15}
	Image:
		source:'hodor.jpg'
		pos_hint:{'x':0,'y':0.4}
		size_hint:0.5,0.5